### PR TITLE
Some instructions on Wifi connecting and discovering the Pi's IP.

### PR DESCRIPTION
**Pull request by paulanthonywilson**
Some instructions on setting up the WiFi. I hadn't really checked the timings and thought I'd have a day in the office before people went to Warsaw.

Note that it is always impossible to connect to conference / hotel WiFi as they use whatsit capture. You know - when a little webpage pops up and you need to enter a code.

You don't need an Internet connection so use a wireless router and make sure it's set up before the conference. Dan's old router is ok, but the Pi does tend to jump IP a lot. I meant to buy an Apple Airport Express, which I believe will work much better and take less space in luggage.

I was intending to order one delivered to the office, but actually it would be much easier if someone could pop into the Apple Store and pick one up.

### CODE REVIEW

**Comment by paulanthonywilson** [comment]
I left a practice Pi on Alan's desk the other week. Also a known good data-cable. The cables that come with the micobits that we got from Eagle Labs are also good for data cables, as are the orange cables that come with the wireless headsets.

**Comment by paulanthonywilson** [comment]
Airport express is available from Princes Street.

**Comment by spencer** [comment]
LGTM: 

For additional ease, I'm wondering if we can use the MAC address of the wifi device on the PI and the DNS server on an airport express to assign a Static IP address.

**Comment by munckymagik** [comment]
Good call, we should try assigning a static IP. Although this does mean a code change, as at this point it's been coded to use DHCP.

**Review by munckymagik — APPROVED** [review]

**Comment by paulanthonywilson** [comment]
Nerves networking only supports DHCP over WiFi. I couldn’t find a way of fixing IP to Max on Dan’s old router firmware. 

Airport routers tend not to jump
IPs around. Also I think the MDNS will work better if someone gets the Airport express.

**Comment by spencer** [comment]
Andy’s got one Paul :)
Thanks for the help and write-up.

Spencer

--
mobile: 07802 443407
email: hello@spencerturner.co.uk
skype: spencerturner twitter: @spencerturner

**Pull request merged**
